---
header_logo_url:  http://Zoraptera.archive.speciesfile.org/HomePage/Zoraptera/img_Logo/SiteLogo.jpg
  header_logo_text: Zoraptera Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
