---
  project_name: "Zoraptera Species File"
  project_citation: "Michael D. Maehr & Heidi Hopkins. Zoraptera Species File. Version 5.0/5.0. [retrieval date]. <http://Zoraptera.SpeciesFile.org>"
  project_authors: "Maehr, M.D. and Hopkins, H."
  project_url: "https://zoraptera.speciesfile.org"
  project_old_url: "https://zoraptera.archive.speciesfile.org" 
  focal_taxon: "zoraptera"
  focal_taxon_common_name: "angel insects"
  contact_email: "cockroachdoc@gmail.com"
